# Generated by Django 5.1.7 on 2025-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('posts', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='post', to='category.category'),
        ),
    ]
