# Generated by Django 5.1.7 on 2025-03-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
