"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
# ������ �б� ���� �ʿ��� ���̺귯���� ��ġ�մϴ�.
from pathlib import Path
import os, json
from django.core.exceptions import ImproperlyConfigured
from datetime import timedelta
import pymysql

pymysql.install_as_MySQLdb()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
secret_file = os.path.join(BASE_DIR, 'secrets.json') 

with open(secret_file) as f:
    secrets = json.loads(f.read())

def get_secret(setting, secrets=secrets): 
# secret ������ �������ų� �׷��� �� �ϸ� ���ܸ� ��ȯ
    try:
        return secrets[setting]
    except KeyError:
        error_msg = "Set the {} environment variable".format(setting)
        raise ImproperlyConfigured(error_msg)

SECRET_KEY = get_secret("SECRET_KEY")


from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    
    ),
}

REST_USE_JWT = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=3),    # 유효기간 3시간
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # 유효기간 7일
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'TOKEN_USER_CLASS': 'accounts.User',
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x$26wlqehc85-!h!*f(iwg%9%t@j1-_-w2a@&zaw^(uxqq2d1%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] #�̰͵� �߾��


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [ 
    'corsheaders.middleware.CorsMiddleware', # �ݵ�� ���� ���ʿ� �߰�
    'posts.logging_middleware.RequestLoggingMiddleware', # �α� �̵���� �߰�
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]
ACCOUNT_LOGIN_METHODS = {'email'}                  # 로그인 방식 설정
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*']    # 회원가입 시 필수 입력 필드 설정

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_PW_local = get_secret("DB_PW_local")

# #로컬
# DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.mysql',
# 		'NAME': "likelion13th",
# 		'USER': "root", # root로 접속하여 DB를 만들었다면 'root'
# 		'PASSWORD': DB_PW_local, # 비밀번호는 secrets.json에 저장
# 		'HOST': 'localhost',
# 		'PORT': '3306',
# 	}
# }
RDS_PW = get_secret("RDS_PW")
...
#원격 연결용
DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': "likelion13th",
		'USER': "admin", # aws에서 만든 사용자명
		'PASSWORD': RDS_PW, # 비밀번호는 secrets.json에 저장
		'HOST': "127.0.0.1",
		'PORT': '3307', # 터널에서 연결할 로컬 포트
	}
}

# EC2서버에서 바로 연결
# DATABASES = {
# 	'default': {
# 		'ENGINE': 'django.db.backends.mysql',
# 		'NAME': "likelion13th",
# 		'USER': "admin", # aws에서 만든 사용자명
# 		'PASSWORD': RDS_PW, # 비밀번호는 secrets.json에 저장
# 		'HOST': "likelion13th.crgcm8c448r8.ap-northeast-2.rds.amazonaws.com", #RDS 엔드포인트
# 		'PORT': '3306', # RDSDB연결
# 	}
# }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

PROJECT_APPS = [
    'posts',
    'accounts',
    'comment',
    'category',
]

THIRD_PARTY_APPS = [ 
    "storages",
    "corsheaders", #���� �־�� ������Ƽ
    "rest_framework",
    'rest_framework_simplejwt',
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google", 
    "drf_yasg",
]




INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS + THIRD_PARTY_APPS
AUTH_USER_MODEL = 'accounts.User'
# ���� ���� ��û(��Ű, ���� ��)�� ���
# ���� ��� �������� �鿣�� ������ ��Ű�� �����ϰų�, �鿣�忡�� ��Ű�� �������� ���� �� ����
CORS_ALLOW_CREDENTIALS = True

# ������ ��û ���� �� �ִ� �����ε� ����
# ���⿡���� localhost�� EC2 �ν��Ͻ��� ����ȯ���� �ƴ϶� ����Ʈ���� ���� ���� ȯ�� �ǹ�
# 3000 ��Ʈ�� ����Ʈ���� React ���ø����̼��� ��Ʈ ��ȣ
# ���� ����Ʈ���忡�� �� ������ ���� �� ������ �����ߴٸ� �ش� ������ �߰� �ʿ�
CORS_ALLOWED_ORIGINS = [ 
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '[{asctime}] [{levelname}] {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_all': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/all_requests.log',
            'formatter': 'verbose',
        },
        'file_error': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'logs/errors.log',
            'formatter': 'verbose',
        },
    },

    'loggers': {
        'request_logger': {
            'handlers': ['console', 'file_all'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file_error'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}
###AWS###
AWS_ACCESS_KEY_ID = get_secret("AWS_ACCESS_KEY_ID") # .csv 파일에 있는 내용을 입력 Access key ID. IAM 계정 관련
AWS_SECRET_ACCESS_KEY = get_secret("AWS_SECRET_ACCESS_KEY") # .csv 파일에 있는 내용을 입력 Secret access key. IAM 계정 관련
AWS_REGION = 'ap-northeast-2'

###S3###
AWS_STORAGE_BUCKET_NAME = 'likelion13th-jaehong'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.%s.amazonaws.com' % (AWS_STORAGE_BUCKET_NAME,AWS_REGION)
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}


