# Generated by Django 5.1.7 on 2025-03-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='categories',
        ),
    ]
